# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.lede.com:

networks:
  byfn:
services:
  orderer.lede.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.lede.com
    container_name: orderer.lede.com
    networks:
      - byfn
