# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.lede.com:
  peer0.org1.lede.com:
  peer1.org1.lede.com:
  peer0.org2.lede.com:
  peer1.org2.lede.com:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.lede.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/5b285696774f8b48ad30cf4913e90f42b0ae5250e6cf55c048baa3e7d8fbad4e_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.lede.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/5b285696774f8b48ad30cf4913e90f42b0ae5250e6cf55c048baa3e7d8fbad4e_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.lede.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.lede.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/2df5e223bf0f2086a9444d15c6e4a3a09a906b3aa5a1a962c64e039c8660dbf8_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.lede.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/2df5e223bf0f2086a9444d15c6e4a3a09a906b3aa5a1a962c64e039c8660dbf8_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.lede.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - byfn

  orderer.lede.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.lede.com
    container_name: orderer.lede.com
    networks:
      - byfn

  peer0.org1.lede.com:
    container_name: peer0.org1.lede.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.lede.com
    networks:
      - byfn

  peer1.org1.lede.com:
    container_name: peer1.org1.lede.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.lede.com
    networks:
      - byfn

  peer0.org2.lede.com:
    container_name: peer0.org2.lede.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.lede.com
    networks:
      - byfn

  peer1.org2.lede.com:
    container_name: peer1.org2.lede.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.lede.com
    networks:
      - byfn
